// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihnbicwphcyqippgtuas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlobmJpY3dwaGN5cWlwcGd0dWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTAzNzQsImV4cCI6MjA3MTU2NjM3NH0.TFI9AWlSrN8E2wQUlholOqqwVKlp0aRShEC9imHowds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});